### ISSUE TITLE
Newer released versions of promruval do not work with go.mod|sum

### ISSUE THREAD

**Issue by burdzwastaken** [FUSAKLA/promruval#28]
Hi,

We are using this project internally and like to store 3rd party tools in a `tools.go` file so that we can run it with other tools such as `bazel`. Unfortunately the latest version(s) of this are `v2.3.1` for example which can not be imported into a go.mod file:

```
replace github.com/fusakla/promruval: version "v2.3.1" invalid: should be v0 or v1, not v2
```

This is by design in golang due to compatibility and how it expects semantic versioning to use a different import path: https://pkg.go.dev/cmd/go#hdr-Module_compatibility_and_semantic_versioning.

Is there plans to support this as I think it would be valuable. Please let me know if you need help with this.

Thanks,

**Comment by FUSAKLA** [comment]
Hi, yes this is a bit unfortunate, but the tool is versioned with the cmd interface in mind.
I'm glad the code is handy event included in your codebase, but the versioning does not take that into account, actually. 

You can solve the issue if you use the commit hash instead of the tag, so for `v2.3.1` use `go get github.com/fusakla/promruval@ a5d6173`

Sorry for the trouble, but I hope this solution is ok?
Please let me know if that works out for you.

**Comment by FUSAKLA** [comment]
Ok, let's bump the version in the go.mod. There is another issue about the same thing and the installation instructions are not working right now, so I agree.

**Comment by FUSAKLA** [comment]
Just released new version which changes the module to `github.com/fusakla/promruval/v2` so you should be able to use the dependency without issues

**Comment by burdzwastaken** [comment]
Thank you so much! I really appreciate your support
