### ISSUE TITLE
Consider implementing support for loki

### ISSUE THREAD

**Issue by jmichalek132** [FUSAKLA/promruval#69]

**Comment by FUSAKLA** [comment]
Since I'm not familiar with the format, could you please elaborate on the differences in the formats?

Can you tell if the file is promehteus or loki rules from the contents? Or would you need to somehow state that those are loki rules? 

Also wondering how much of the validations would it be possible to reuse :thinking: Because if the intersection will be small to none, I'm not sure if it is the right path to go adding i to this tool even thought I do understand it is appealing.

**Comment by FUSAKLA** [comment]
Hm looking swiftly into the loki docs https://grafana.com/docs/loki/latest/alert/#alerting-and-recording-rules it appears that the difference is mainly just the query syntax, but otherwise it looks like the file syntax for rules and alerts is practically the same (or subset of the fields allowed by promehteus)

So I do see the benefit of adding it to promruval since all the validations except for those on expression would work for it.

The question is how to do the user interface and if you would like to add also some validation for logql expressions?

I se there is parser for the logql same as for prometheus so it should be possible https://pkg.go.dev/github.com/grafana/loki/pkg/logql#ParseExpr

**Comment by FUSAKLA** [comment]
In theory it could try to parse the query as PromQL and if it fails treat it as LogQL.
We do this partially with the allowed fields for thanos(`partial_response_strategy`) or mimir(`source_tenants`) with the idea to reduce number of configuration nobs.

Otherwise we would have to introduce some subcommand like `promruval validate loki` or flag `promruval validate --loki` :thinking:

**Comment by FUSAKLA** [comment]
Well, it showed up that you could actually use promruval to validate loki rules already just those validators that check `expr` wouldn't work

I created this PR to officially add support for it (some custom fields in rule files) and first validators for LogQL

So this way any other validator should be applicable to the Loki rules and you can add custom LogQL validators in next PRs

https://github.com/FUSAKLA/promruval/pull/74
